# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Péter Sipos
title: Software engineer wannabe/Student
email: sipos.peter@sysconet.hu
website: https://siposptr.github.io

# Social links
github_username:  SiposPtr
instagram_username: siposptr99

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Péter and I'm a High School Student from Hungary. I don't have any kind of work experience unfortunately.
  I love learning languages.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Karate
   - Any other kind of sports
   - Workout

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
